name: uberbot-CI
on:
  [push]
jobs:
  verifying-code:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Format Code
        uses: actions/checkout@v2
      - name: Check diff between gofmt and code
        run: go fmt ./...
      - name: Vet Code
        run: go vet -x ./...
      - name: GolangCI-Lint
        uses: golangci/golangci-lint-action@v2.5.2
        if: github.event.name == 'pull_request'
        with:
          only-new-issues: true
          skip-pkg-cache: true
          skip-build-cache: true
      - name: GolangCI-Lint
        if: github.event.name != 'pull_request' # See https://github.com/golangci/golangci-lint-action/issues/362
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.43.0
          $(go env GOPATH)/bin/golangci-lint run
